### ISSUE TITLE
Crash on joining world (log snippet included)

### ISSUE THREAD

**Issue by hairlessOrphan** [timinc-cobble/cobblemon-unchained-1.5-forge#1]
Joining a new world with a fresh install with Cobblemon 1.5, Counter 1.5, and Unchained 1.5 causes a crash:

[01:25:28] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: us/timinc/mc/config/ConfigBuilder
	at us.timinc.mc.cobblemon.chaining.Chaining$Registration.onInit(Chaining.kt:28) ~[cobblemon-unchained-1.5-forge-1.0.0.jar%23561!/:?]
	at us.timinc.mc.cobblemon.chaining.__Registration_onInit_ServerStartedEvent.invoke(.dynamic) ~[cobblemon-unchained-1.5-forge-1.0.0.jar%23561!/:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.server.ServerLifecycleHooks.handleServerStarted(ServerLifecycleHooks.java:115) ~[forge-1.20.1-47.2.21-universal.jar%23835!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:638) ~[client-1.20.1-20230612.114412-srg.jar%23830!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23830!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: us.timinc.mc.config.ConfigBuilder
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	... 9 more

**Comment by tmetcalfe89** [comment]
You got ahead of me lol. I just fixed Capture XP and Counter so they wouldn't butt heads on config logic on Forge, but as a result, yeah, I need to have Unchained point at its own config logic. Took a nap, ate some dinner, working on this one.

**Comment by tmetcalfe89** [comment]
Fix coming in fix for #2
